behaviors:
  Lemmings:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 5000000
    time_horizon: 128
    summary_freq: 10000
    threaded: true
env_settings:
    env_path: .\Lemmings_lvl6.2\SimpleLemmings.exe
    num_envs: 4
engine_settings:
    width: 320
    height: 180
    time_scale: 20
    no_graphics: false
checkpoint_settings:
    run_id: lemmings_19
    initialize_from: null
    resume: true
    # force: true